package org.ual.hmis.sailsapp;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
public class LoginwrongpasswordTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	@Before
	public void setUp() {

		System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe"); 

		System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe"); 
		driver = new FirefoxDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		
		// Waiting 30 seconds for an element to be present on the page, checking
		// for its presence once every 5 seconds.
		Wait<WebDriver> wait = new FluentWait<WebDriver>(driver)
		  .withTimeout(Duration.ofSeconds(30))
		  .pollingEvery(Duration.ofSeconds(5))
		  .ignoring(NoSuchElementException.class);
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	@Test
	public void loginwrongpassword() {
		driver.get("http://localhost:1337/");
		driver.manage().window().setSize(new Dimension(764, 824));
		driver.findElement(By.linkText("Log in")).click();
		driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).sendKeys("jjcanada@ual.es");
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("hola");
		driver.findElement(By.cssSelector(".ajax-button")).click();
		{
			List<WebElement> elements = driver.findElements(By.xpath("//small[contains(.,\'The credentials you entered are not associated with an account. Please check your email and/or password and try again.\')]"));
			assert(elements.size() > 0);
		}
	}
}
