package org.ual.selenium.hmis;


// Generated by Selenium IDE
import static org.junit.jupiter.api.Assertions.fail;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvFileSource;
import org.junit.jupiter.params.provider.CsvSource;


import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.hamcrest.MatcherAssert.assertThat;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
public class WebualgradoinginfTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	static JavascriptExecutor js;
	
	@BeforeAll
	public static void setUpAll() {
		// Firefox 
		// Descargar geckodriver de https://github.com/mozilla/geckodriver/releases
		// Descomprimir el archivo geckodriver.exe en la carpeta drivers
		System.setProperty("webdriver.gecko.driver",  "drivers/geckodriver.exe");

		// Chrome
		// Descargar Chromedriver de https://chromedriver.chromium.org/downloads
		// Descomprimir el archivo chromedriver.exe en la carpeta drivers
		System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");

		
	}
	// @BeforeEach
	public void setUp(int browser, boolean headless) {
		// Browser selector 
		// int browser= 0; // 0: firefox, 1: chrome,...
		// Boolean headless = true;
		
		switch (browser) {
		case 0:  // firefox
			FirefoxOptions firefoxOptions = new FirefoxOptions();
			if (headless) firefoxOptions.setHeadless(headless);
			driver = new FirefoxDriver(firefoxOptions);

			break;
		case 1: // chrome
			ChromeOptions chromeOptions = new ChromeOptions();
			if (headless) chromeOptions.setHeadless(headless);
			// chromeOptions.addArguments("window-size=1920,1080");
			driver = new ChromeDriver(chromeOptions);

			break;

		default:
			fail("Please select a browser");
			break;
		}
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	@AfterEach
	public void tearDown() {
		driver.quit();
	}
	
	@ParameterizedTest (name = "{index} => [{0}, headless: {1}] {2}")
	@CsvSource({"0, true, Tratamiento Digital de Imágenes", 
			    "1, false, Modelado y Diseño del Software 2", 
			    "0, true, Modelado y Diseño del Software 2", 
			    "1, true, Introducción a la Programación",
			    "0, true, Herramientas y Métodos de Ingeniería del Software"})
	
	public void ualcourseBrowser(int browser, boolean headless, String course) {
		this.setUp(browser, headless);
		
		// Test name: tdi-ual
		// Step # | name | target | value
		// 1 | open | / | 
		driver.get("https://www.ual.es/");
	    // 2 | setWindowSize | 1251x740 | 
	    driver.manage().window().setSize(new Dimension(1251, 740));
	    
	    // Bloque de pulsar a boton aceptar, por si aparece 
	    try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
	    
	    // | storeXpathCount | xpath=//button[contains(.,'Guardar')] | botonGuardar
	    vars.put("botonGuardar", driver.findElements(By.xpath("//button[contains(.,\'Guardar\')]")).size());
	    // | echo | boton ${botonGuardar} | 
	    System.out.println("boton "+ vars.get("botonGuardar").toString());
	    // | if | ${botonGuardar}>0 | 
	    if ((Boolean) js.executeScript("return (arguments[0]>0)", vars.get("botonGuardar"))) {
	      // | click | css=.btn-accept | 
	      driver.findElement(By.cssSelector(".btn-accept")).click();
	      // | end |  | 
	    }

	    
		// 3 | click | linkText=Estudios | 
		driver.findElement(By.linkText("Estudios")).click();
		// 4 | click | linkText=Grados | 
		try {
			Thread.sleep(1000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.linkText("Grados")).click();
	    // 5 | click | xpath=//span[contains(.,'Grado en Ingeniería Informática (Plan 2015)')] | 
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
			wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[contains(.,\'Grado en Ingeniería Informática (Plan 2015)\')]")));
		}

		try {
			Thread.sleep(1000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

		driver.findElement(By.xpath("//span[contains(.,\'Grado en Ingeniería Informática (Plan 2015)\')]")).click();		
	    // 6 | click | linkText=Plan de Estudios | 
		try {
			Thread.sleep(1000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

		driver.findElement(By.linkText("Plan de Estudios")).click();
		// 7 | click | linkText=Asignaturas | 
		try {
			Thread.sleep(1000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.linkText("Asignaturas")).click();
		// 8 | assertText | linkText=Tratamiento Digital de Imágenes | Tratamiento Digital de Imágenes
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
			wait.until(ExpectedConditions.elementToBeClickable(By.linkText(course)));
		}
		assertThat(driver.findElement(By.linkText(course)).getText(), is(course));
	}

}
